vizen-module-user:
  userfile: /Users/majianhua/work/myidea/pano-public-sys/server/vizen-module-user/src/main/resources/usersettings.yml

spring:
  redis:
    host: redis
    port: 6379
    password: vb2015redis
    pool:
      maxTotal: 8
      minIdle: 1
      maxActive: 8
      maxWait: -1