spring:
  datasource:
    url: jdbc:mysql://192.168.0.143:3306/db_shunde?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 

mark-framework:
  cosConfig:
    root: /ztspcard/dev
    bucket: material
  elasticsearch:
    enable:
    host: 10.154.210.98
    port: 9300
    cluster:
      name: elasticsearch


