variables:
  DIST_DIR_NAME: lingju-manage
  #DEPLOY_HOST_DEV: 192.168.1.212
  DEPLOY_HOST_TEST: 192.168.1.211
  #DEPLOY_HOST_PROD: 10.66.92.7

cache:
  paths:
  - node_modules/
  - dist/

stages:
  - install
  - build
  - upload
  - deploy

# ================================ install start ================================

# install

#dev-install:
#  stage: install
#  only:
#    - dev
#  script:
#    - cnpm install
#  tags:
#    - dev

test-install:
  stage: install
  only:
    - release
  script:
    - cnpm install
  tags:
    - test

#prod-install:
#  stage: install
#  only:
#    - master
#  script:
#    - cnpm install
#  tags:
#    - prod

# ================================ install end ================================


# ================================ build start ================================

# build
#dev-build:
#  stage: build
#  only:
#    - dev
#  script:
#    - rm -rf dist/$DIST_DIR_NAME
#    - rm -f dist/$DIST_DIR_NAME.zip
#    - cnpm run build dev
#    - cd dist
#    - zip -qr $DIST_DIR_NAME.zip $DIST_DIR_NAME
#  tags:
#    - dev

test-build:
  stage: build
  only:
    - release
  script:
    - rm -rf dist/$DIST_DIR_NAME
    - rm -f dist/$DIST_DIR_NAME.zip
    - cnpm run build test
    - cd dist
    - zip -qr $DIST_DIR_NAME.zip $DIST_DIR_NAME
  tags:
    - test

#prod-build:
#  stage: build
#  only:
#    - master
#  script:
#    - rm -rf dist/$DIST_DIR_NAME
#    - rm -f dist/$DIST_DIR_NAME.zip
#    - cnpm run build prod
#    - cd dist
#    - zip -qr $DIST_DIR_NAME.zip $DIST_DIR_NAME
#  tags:
#    - prod

# ================================ build end ================================


# ================================ upload start ================================

# upload
#dev-upload:
#  stage: upload
#  only:
#    - dev
#  script:
#    - scp dist/$DIST_DIR_NAME.zip root@$DEPLOY_HOST_DEV:~/artifacts
#  tags:
#    - dev

test-upload:
  stage: upload
  only:
    - release
  script:
    - scp dist/$DIST_DIR_NAME.zip root@$DEPLOY_HOST_TEST:~/artifacts
  tags:
    - test

#prod-upload:
#  stage: upload
#  only:
#    - master
#  script:
#    - scp dist/$DIST_DIR_NAME.zip root@$DEPLOY_HOST_PROD:~/artifacts
#  tags:
#    - prod

# ================================ upload end ================================


# ================================ deploy start ================================

# deploy-biz-service
#dev-deploy-biz-service:
#  stage: deploy
#  only:
#    - dev
#  script:
#  - ssh root@$DEPLOY_HOST_DEV "~/deploy-script/deploy-lingju-manage.sh"
#  tags:
#    - dev

test-deploy-biz-service:
  stage: deploy
  only:
    - release
  script:
    - ssh root@$DEPLOY_HOST_TEST "~/deploy-script/deploy-lingju-manage.sh"
  tags:
    - test

#prod-deploy-biz-service:
#  stage: deploy
#  only:
#    - master
#  script:
#    - ssh root@$DEPLOY_HOST_PROD "~/deploy-script/deploy-lingju-manage.sh"
#  tags:
#    - prod

# ================================ deploy end ================================
