spring:
  datasource:
    url: jdbc:mysql://10.66.110.250:3306/zts_pcard?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 832f27F11C90481c

mark-framework:
  cosConfig:
    root: /ztspcard/test
    bucket: material
  elasticsearch:
    host: 10.154.210.98
    port: 9300
    cluster:
      name: elasticsearch