- unique_id: mark
  data:
    secret: "123456"
    unique_id: "mark"
    luna_name: "mark"
    real_name: "mark"
    menu_auth:
      /data/album:
        auth: "pano-viewer:login:*,pano-viewer:album:*,pano-viewer:pano:*,cos:panomedias:write,pano-news:login:*,pano-news:album:*,pano-news:pano:*"
- unique_id: pingtan_test
  data:
    secret: "pingtan_test_123456"
    unique_id: "pingtan_test"
    luna_name: "pingtan_test"
    real_name: "pingtan_test"
    menu_auth:
      /data/album:
        auth: "pano-viewer:login:*,pano-viewer:album:*,pano-viewer:pano:*,cos:panomedias:write,pano-news:login:*,pano-news:album:*,pano-news:pano:*"

- unique_id: pingtan
  data:
    secret: "pingtan_123456"
    unique_id: "pingtan"
    luna_name: "pingtan"
    real_name: "pingtan"
    menu_auth:
      /data/album:
        auth: "pano-viewer:login:*,pano-viewer:album:*,pano-viewer:pano:*,cos:panomedias:write,pano-news:login:*,pano-news:album:*,pano-news:pano:*"

- unique_id: shunde
  data:
    secret: "shunde_123456"
    unique_id: "shunde"
    luna_name: "shunde"
    real_name: "shunde"
    menu_auth:
      /data/album:
        auth: "pano-viewer:login:*,pano-viewer:album:*,pano-viewer:pano:*,cos:panomedias:write,pano-news:login:*,pano-news:album:*,pano-news:pano:*"
